### ISSUE TITLE
Point Cloud Development Sprint Week of 10/16/17

### ISSUE THREAD

**Issue by sslattery** [ORNL-CEES/DataTransferKit#312]
Outline of sprint work for point cloud development:

- [x] Test Tpetra import/export capability to clearly define global id and unique point requirements. This will also demonstrate building Tpetra vectors from Kokkos views of input user data.

- [x] Define point cloud test problems for both surface and volume transfers.

- [x] Develop abstract test problem generator interface with preliminary implementations. Outputs of problem generator should allow for the testing of parallel code.

- [x] Build unit tests with abstract problem generator

- [x] Develop nearest neighbor operator. Covered by #217 with final work in #219 

- [x] Develop batched dense linear algebra operations needed for moving least square operations. Capabilities available covered in #283 

- [x] Develop moving least square operator covered in #281.

**Comment by sslattery** [comment]
Some notes on the abstract problem generator:
- Example outputs might be an `MPI_Comm` handle, a view of output point coordinates, and a view of multi-component data assigned to the points.
- A specific implementation could be randomly building points in a volume or over a surface and then using Zoltan to partition the results.
- A callable object to define the data assigned to the points would be useful

**Comment by sslattery** [comment]
Will use `oneToOne` functionality it `Tpetra::Map` to handle ghosted-to-ghosted communication plans.

**Comment by sslattery** [comment]
All core capabilities have been developed. Waiting to merge #352
